all: clean task1 task2 task3 task4

task1: task1.c
	gcc task1.c -o task1 -Wall

task2: task2.c
	gcc task2.c -o task2 -Wall

task3: task3.c
	gcc task3.c -o task3 -Wall

task4: task4.c
	gcc task4.c -o task4 -Wall

clean: 
	rm task1 task2 task3 task4



