hello: hello.c
	gcc hello.c -o hello -std=c99 -Wall

cnhello: cnhello.c
	gcc cnhello.c -o cnhello -std=c99 -Wall

triangle: triangle.c
	gcc triangle.c -o triangle -std=c99 -Wall

circle: circle.c
	gcc circle.c -o circle -std=c99 -Wall
