task1: task1.c
	gcc task1.c -o task1 -std=c99 -Wall

task2: task2.c
	gcc task2.c -o task2 -std=c99 -Wall

task3: task3.c
	gcc task3.c -o task3 -std=c99 -Wall

task4: task4.c
	gcc task4.c -o task4 -std=c99 -Wall

task5: task5.c
	gcc task5.c -o task5 -std=c99 -Wall
